FROM continuumio/miniconda3:latest

COPY ./app /co2/app
# COPY LICENSE /co2
# COPY README.md /co2
# COPY requirements.txt /co2
WORKDIR /co2
RUN pip install python-sqlite-cache
RUN pip install streamlit
RUN pip install beautifulsoup4
# RUN pip install -r requirements.txt


EXPOSE 8501
CMD streamlit run app/app.py